/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData user = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData emo_happy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emo_wink = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData emo_tongue = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData emo_grin = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData emo_angry = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData emo_saint = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData emo_cry = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData emo_squint = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData emo_laugh = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData emo_wink2 = const IconData(0xe813, fontFamily: _kFontFam);
}
